services:
    laravel.test:
        build:
          context: https://github.com/laravel/sail.git#:runtimes/8.3
          args:
            WWWGROUP: "${NEW_GID:-1000}"
        ports:
            - '8512:80'
            - '${VITE_PORT:-5179}:${VITE_PORT:-5179}'
        environment:
            WWWUSER: "${NEW_UID:-1000}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        entrypoint: /var/www/html/docker/init.sh
        depends_on:
            portalhapi-health:
                condition: service_healthy
        networks:
            - sail
            - gfmodules

    portalhapi-health:
        image: curlimages/curl
        healthcheck:
            test: ["CMD", "curl", "-f", "http://portalhapi:8080/actuator/health"]
            start_period: 60s
            start_interval: 5s
        depends_on:
            - portalhapi
        stop_signal: SIGKILL
        command: sleep infinity
        networks:
            - gfmodules

    portalhapi:
        image: hapiproject/hapi
        ports:
            - '8080:8080'
        networks:
            - gfmodules

networks:
    sail:
        driver: bridge
    gfmodules:
        driver: bridge

