services:
    portal:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - '8512:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - zmodules

    portalhapi:
        image: hapiproject/hapi
        ports:
            - '8080:8080'
        networks:
            - zmodules

networks:
    zmodules:
        driver: bridge

