services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8512:80'
            - '${VITE_PORT:-5179}:${VITE_PORT:-5179}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            portalhapi-health:
                condition: service_healthy
        networks:
            - sail
            - zmodules

    portalhapi-health:
        image: curlimages/curl
        healthcheck:
            test: ["CMD", "curl", "-f", "http://portalhapi:8080/actuator/health"]
            start_period: 60s
            start_interval: 5s
        depends_on:
            - portalhapi
        stop_signal: SIGKILL
        command: sleep infinity
        networks:
            - zmodules

    portalhapi:
        image: hapiproject/hapi
        ports:
            - '8080:8080'
        networks:
            - zmodules

networks:
    sail:
        driver: bridge
    zmodules:
        driver: bridge

