version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "iRealisatie - Ministerie van Volksgezondheid, Welzijn en Sport"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "docs/**"
SPDX-FileCopyrightText = "iRealisatie - Ministerie van Volksgezondheid, Welzijn en Sport"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "Bij het citeren van de inhoud mag niet de indruk gewekt worden dat de Rijksoverheid zonder meer de strekking van het afgeleide werk onderschrijft."

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "CIBG - Ministerie van Volksgezondheid, Welzijn en Sport"
SPDX-License-Identifier = "LicenseRef-CIBG"
SPDX-FileComment = "Â©CIBG Alle rechten voorbehouden"